CREATE DATABASE EVENT_MONITOR;
CREATE TABLE IF NOT EXISTS "EVENT" (
    "TIMESTAMP" timestamp(0) NOT NULL,
    "TAG" varchar NOT NULL,
    "VALUE" varchar NOT NULL,
    CONSTRAINT event_pk PRIMARY KEY ("TIMESTAMP", "TAG", "VALUE")
);