version: '3'
services:
  api:
    image: event-monitor
    env_file:
    - .env
    build:
      context: "./server"
      dockerfile: "./Dockerfile"
    container_name: event-monitor    
    ports:
      - 5000:80
    restart: unless-stopped
    volumes:  
      - "./data:/app/data"
  db:
    container_name: postgres
    env_file:
      - .env
    image: postgres:9.6
    ports:
      - 5432:5432
    restart: always
    volumes:
      - "./data:/var/lib/postgresql/data"
      - "./db.sql:/docker-entrypoint-initdb.d/init.sql"
  simulator:
    image: event-simulator
    env_file:
    - .env
    build:
      context: "./simulator"
      dockerfile: "./Dockerfile"
    container_name: event-simulator
    restart: unless-stopped